# Generated by Django 3.2.22 on 2024-02-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='courses',
            field=models.ManyToManyField(related_name='Course', to='api.Course'),
        ),
    ]
